apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Mi

---

apiVersion: batch/v1
kind: Job
metadata:
  name: ovpn-genconfig 
spec:
  template:
    spec:
      containers:
      - name: ovpn-genconfig 
        image: kylemanna/openvpn
        args:
        - "ovpn_genconfig"
        - "-u"
        - "udp://serg046.dev"
        volumeMounts:
        - name: ovpn-data-volume
          mountPath: /etc/openvpn
      volumes:
      - name: ovpn-data-volume
        persistentVolumeClaim:
          claimName: local-path-pvc
      restartPolicy: Never

---

apiVersion: batch/v1
kind: Job
metadata:
  name: ovpn_initpki
spec:
  template:
    spec:
      containers:
      - name: ovpn_initpki
        image: kylemanna/openvpn
        command:
        - "sh"
        - "-c"
        - >
          ovpn_initpki 
        volumeMounts:
        - name: ovpn-data-volume
          mountPath: /etc/openvpn
      volumes:
      - name: ovpn-data-volume
        persistentVolumeClaim:
          claimName: local-path-pvc
      restartPolicy: Never