apiVersion: v1
kind: Service
metadata:
  name: ipsec-vpn-server-lb
spec:
  type: LoadBalancer
  - port: 500
    protocol: UDP
    targetPort: 500
  - port: 4500
    protocol: UDP
    targetPort: 4500
  selector:
    app: ipsec-vpn-server
